version: '3'
services:
  observe-siem-demo:
    build: .
    container_name: observe-siem-demo
    environment:
      OBSERVE_ENDPOINT: "https://OBSERVE_ENDPOINT"
      AUTH_TOKEN: "OBSERVE_TOKEN"
    restart: unless-stopped
